version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"

    # 开发模式配置
    working_dir: /app/src
    entrypoint: ['python', 'app.py']
    volumes:
      - .:/app
      #- ./runtest:/bin/runtest
    command: []
    tty: true
