version: '3.1'

services:
  flask-hello-prod:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-Prod
    ports:
      - "5000:5000"
    environment: 
      FLASK_RUN_PORT: 5000
    working_dir: /app/src
    volumes:
      - .:/app
    entrypoint: ['gunicorn', '-c', 'etc/gunicorn_config.py', "app:app"]

