version: '3.1'

services:
  flask-hello:
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        ENV_LANG: CN
        COMPOSE_MODE: PROD
    env_file: ./envs/prod.env
    environment: 
      FLASK_RUN_PORT: 5000
    ports:
      - "5000:5000"
    working_dir: /app/src
    volumes:
      - .:/app
    entrypoint: ['gunicorn', '-c', 'etc/gunicorn_config.py', "app:app"]

