name: Deploy

on:
  workflow_run:
    # Publish `master` as Docker `latest` image.
    workflows: ["Docker"]
    branches: [master]
    types: 
      - completed


env:
  # TODO: Change variable to your image's name.
  USER_IMAGE_NAME: clarkchenme/flask-hello
  IMAGE_NAME: flask-hello

jobs:
  build:
    name: Build
    environment: Product
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo  ${{ secrets.HOST }}
    
    - name: test IMAGE_NAME
      run: echo $IMAGE_NAME

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host:  ${{ secrets.HOST }}
        username:  ${{ secrets.SSH_USER }} 
        password:  ${{ secrets.SSH_USER_PWD }}
        port: 22
        envs: IMAGE_NAME,USER_IMAGE_NAME
        script: |
          echo $IMAGE_NAME
          docker container stop $(docker container ls|awk "/$IMAGE_NAME/{print $1}")
          docker pull $USER_IMAGE_NAME
          docker run -p 5000:5000 -d $USER_IMAGE_NAME

